### ISSUE TITLE
Issue while running playbook locally on a RHEL8 CSB machine while running the task "Start the Quadlet Demo Service]"

### ISSUE THREAD

**Issue by rrbanda** [ygalblum/quadlet-demo#25]
Steps Followed

Updated the playbook header with llocalhost as shown below

```
- name: Setup quadlet demo machine
  hosts: 127.0.0.1
  connection: local
  become: true
```

Error after running `ansible-playbook playbook.yml` as below 

TASK [Start the Quadlet Demo Service] ************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Could not find the requested service quadlet-demo: host"}

PLAY RECAP ***************************************************************************************************************************************************
127.0.0.1                  : ok=17   changed=0    unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

**Comment by rrbanda** [comment]
@ygalblum  Please suggest

**Comment by ygalblum** [comment]
What distribution and version are you using? What version of Podman is installed?

**Comment by rrbanda** [comment]
podman version related issue but closing this to open another one when i ran this one on centos9
