### ISSUE TITLE
Vagrant setup for testing this quickly

### ISSUE THREAD

**Issue by johanneskastl** [ygalblum/quadlet-demo#3]
Hi,

first of all, thanks for the nice idea. Very interesting.

To quickly try this out, I prepared a Vagrant setup using vagrant-libvirt and a CentOS9 Stream VM.
https://github.com/johanneskastl/quadlet-demo_vagrant_libvirt

In case this is of interest, I can prepare a PR for this repository to just add the Vagrantfile directly.

**Comment by ygalblum** [comment]
Looks great. Adding it will be very nice. Thanks
